//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waSysColegio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int ID_Asistencia { get; set; }
        public string Nombre_Tipo_Asistencia { get; set; }
        public int ID_Estudiante { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Estado_Registro { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
