//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waSysColegio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Curso
    {
        public int ID_Estudiante { get; set; }
        public int ID_Curso { get; set; }
        public int ID_Periodo { get; set; }
        public Nullable<decimal> Competencia1 { get; set; }
        public Nullable<decimal> Competencia2 { get; set; }
        public Nullable<decimal> Competencia3 { get; set; }
        public Nullable<decimal> Competencia4 { get; set; }
        public Nullable<decimal> Proyecto { get; set; }
        public Nullable<decimal> ExamenFinal { get; set; }
        public string Estado_Registro { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
