//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waSysColegio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColegioBDv2Entities : DbContext
    {
        public ColegioBDv2Entities()
            : base("name=ColegioBDv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apoderado> Apoderado { get; set; }
        public virtual DbSet<Apoderado_Estudiante> Apoderado_Estudiante { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Detalle_Curso> Detalle_Curso { get; set; }
        public virtual DbSet<Estado_Usuario> Estado_Usuario { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<Tipo_Personal> Tipo_Personal { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
